# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT
name: Format Check
on: pull_request

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Execute copyright check
        run: ./scripts/run-copyright-check.sh

      - name: Install tree sitter library
        run: |
          npm cache clean --force
          npm install tree-sitter@0.16.1
          npm install tree-sitter-rust@0.16.0

      - name: Check TS code formatting
        run: |
          npm install -g npm@latest
          npm install
          npm run lint
